# Generated by Django 3.2 on 2021-04-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Событие')),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='Картинка')),
                ('content', models.TextField(max_length=1500, verbose_name='Описание события')),
                ('file_field', models.FileField(upload_to='file', verbose_name='Файл')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
